// Generated by dts-bundle-generator v9.5.1

export type Callback = (data: { time: number; delta: number }) => void;
declare function useAnimationFrame(cb: Callback): void;

export { useAnimationFrame as default };

export {};
